# -*- coding : UTF-8 -*-
from function import *

def main(): # la solution du labyrinthe
    avance(7)
    tourne_droite()
    avance(4)
    tourne_droite()
    avance(6)
    tourne_gauche()
    avance(6)
    tourne_gauche()
    avance(12)
    tourne_droite()
    avance(4)
    tourne_gauche()
    avance(6)
    tourne_gauche()
    avance(19)
    tourne_gauche()
    avance(8)
    tourne_gauche()
    avance(3)
    tourne_droite()
    avance(10)
    tourne_droite()
    avance(2)
    tourne_droite()
    avance(8)
    tourne_gauche()
    avance(3)
    tourne_droite()
    avance(8)
    tourne_gauche()
    avance(2)
    tourne_gauche()
    avance(10)
    tourne_gauche()
    avance(3)
    tourne_droite()
    avance(4)
    tourne_droite()
    avance(5)
    tourne_droite()
    avance(17)
